# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evaluacion', '0001_initial'),
        ('convocado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='convocado_conv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.IntegerField()),
                ('convocado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convocado.convocado')),
                ('convocatoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.convocatoria')),
            ],
        ),
        migrations.CreateModel(
            name='convocado_evid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidencia', models.CharField(max_length=30)),
                ('numero_evid', models.CharField(blank=True, max_length=15, null=True)),
                ('cargo_rol', models.CharField(max_length=60)),
                ('valor', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('puntaje', models.IntegerField()),
                ('caracteristica_conv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.caracteristica_conv')),
                ('convocatoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.convocatoria')),
            ],
        ),
        migrations.CreateModel(
            name='tipo_evidencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='convocado_evid',
            name='tipo_evidencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evidencia.tipo_evidencia'),
        ),
    ]
