# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='caracteristica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('estado', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='caracteristica_conv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_max', models.IntegerField()),
                ('caracteristica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.caracteristica')),
            ],
        ),
        migrations.CreateModel(
            name='convocatoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=10, unique=True)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True)),
                ('estado', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='item_conv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_max', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.item')),
            ],
        ),
        migrations.CreateModel(
            name='rubro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True)),
                ('estado', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='rubro_conv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.IntegerField()),
                ('convocatoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.convocatoria')),
                ('rubro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.rubro')),
            ],
        ),
        migrations.AddField(
            model_name='item_conv',
            name='rubro_conv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.rubro_conv'),
        ),
        migrations.AddField(
            model_name='caracteristica_conv',
            name='item_conv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.item'),
        ),
    ]
