# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caracteristica',
            name='nombre',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='nombre',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
