# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0002_auto_20160517_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='caracteristica_conv',
            name='cantidad',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='caracteristica_conv',
            name='puntaje',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
