# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0004_auto_20160518_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caracteristica_conv',
            name='item_conv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.item_conv'),
        ),
    ]
