# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0005_auto_20160520_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='caracteristica_conv',
            name='numeracion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item_conv',
            name='numeracion',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rubro_conv',
            name='numeracion',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
