# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0013_auto_20160529_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caracteristica',
            name='nombre',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
