# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0014_auto_20160529_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='det_caracteristica_conv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.IntegerField(blank=True, null=True)),
                ('puntaje', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('factor', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='caracteristica_conv',
            old_name='puntaje',
            new_name='puntaje_fact',
        ),
        migrations.RemoveField(
            model_name='caracteristica_conv',
            name='cantidad',
        ),
        migrations.AddField(
            model_name='caracteristica_conv',
            name='factor',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='caracteristica_conv',
            name='puntaje_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='det_caracteristica_conv',
            name='caracteristica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.caracteristica_conv'),
        ),
    ]
