# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-03 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0017_remove_caracteristica_conv_sub_caract'),
    ]

    operations = [
        migrations.AddField(
            model_name='convocatoria',
            name='estado',
            field=models.CharField(default='1', max_length=1),
            preserve_default=False,
        ),
    ]
