# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 19:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convocado', '0002_auto_20160526_1259'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='evidencia_aconvocatoria',
            new_name='evidencia_convocatoria',
        ),
    ]
