# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocado', '0004_auto_20160613_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubigeo',
            name='nombre',
            field=models.CharField(max_length=40),
        ),
    ]
