# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-17 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocado', '0007_persona_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='foto',
            field=models.ImageField(upload_to='foto_perfil/'),
        ),
    ]
