# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-20 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocado', '0008_auto_20160617_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidencia_convocatoria',
            name='puntaje_obte',
        ),
        migrations.AddField(
            model_name='evidencia_convocatoria',
            name='puntaje_obtenido',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
