# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-20 01:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convocado', '0009_auto_20160619_1959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evidencia_convocatoria',
            old_name='convocado',
            new_name='convocado_convocatoria',
        ),
    ]
