# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-22 22:34
from __future__ import unicode_literals

import apps.convocado.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocado', '0011_auto_20160619_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidencia_convocatoria',
            name='evidencia',
            field=models.ImageField(upload_to=apps.convocado.models.generate_filename),
        ),
    ]
