# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-23 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocado', '0012_auto_20160622_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencia_convocatoria',
            name='estado_eval',
            field=models.CharField(default='0', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evidencia_convocatoria',
            name='puntaje_calculado',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evidencia_convocatoria',
            name='tiempo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
