# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-26 22:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('convocado', '0014_auto_20160624_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('ap_pat', models.CharField(max_length=30)),
                ('ap_mat', models.CharField(max_length=30)),
                ('foto', models.ImageField(upload_to='foto_perfil/')),
                ('dni', models.CharField(max_length=8)),
                ('fecha_nac', models.DateTimeField()),
                ('estado_civil', models.CharField(max_length=1)),
                ('sexo', models.CharField(max_length=1)),
                ('direccion', models.CharField(max_length=50)),
                ('ubigeo', models.CharField(max_length=6)),
                ('direccion_act', models.CharField(max_length=50)),
                ('telefono', models.CharField(blank=True, max_length=10, null=True)),
                ('celular', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('ubigeo_act', models.CharField(max_length=6)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='convocado',
            name='persona',
        ),
        migrations.AlterField(
            model_name='convocado_convocatoria',
            name='convocado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convocado.perfil'),
        ),
        migrations.DeleteModel(
            name='convocado',
        ),
        migrations.DeleteModel(
            name='persona',
        ),
    ]
