# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-27 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocado', '0016_auto_20160627_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='foto_perfil/'),
        ),
    ]
