# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocado', '0018_auto_20160627_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencia_convocatoria',
            name='item',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
