# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-29 00:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('convocado', '0019_evidencia_convocatoria_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidencia_convocatoria',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.item_conv'),
        ),
    ]
