# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-30 15:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convocado', '0020_auto_20160628_1910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evidencia_convocatoria',
            old_name='item',
            new_name='item_conv',
        ),
    ]
