# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-03 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocado', '0024_convocado_convocatoria_estado_conv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='dni',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='email',
            field=models.EmailField(blank=True, max_length=50, unique=True),
        ),
    ]
